apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:4.1.0-management
          ports:
            - containerPort: 15672
              name: port-rabbitmq-mgnt
///////////////////// Falta definir desde acá
---
apiVersion: v1
kind: Service
metadata:
  name: plataforma-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: plataformaservice
  ports:
    - name: plataformaservice
      protocol: TCP
      port: 8080
      targetPort: 8080